### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by agnunez** [GuLinux/AstroPhoto-Plus#64]
I have tried to test the stable release following wiki in a server running:

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

as wiki:

sudo apt install ./StarQuew-0.1.1-b209-Linux.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'starquew' instead of './StarQuew-0.1.1-b209-Linux.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 starquew : Depends: python3-venv but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I also tried dpkg directly:

$ sudo dpkg -i StarQuew-0.1.1-b209-Linux.deb
Selecting previously unselected package starquew.
(Reading database ... 233386 files and directories currently installed.)
Preparing to unpack StarQuew-0.1.1-b209-Linux.deb ...
Unpacking starquew (0.1.1-b209) ...
dpkg: dependency problems prevent configuration of starquew:
 starquew depends on python3-venv; however:
  Package python3-venv is not installed.
 starquew depends on libatlas-base-dev; however:
  Package libatlas-base-dev is not installed.
 starquew depends on libopencv-dev; however:
  Package libopencv-dev is not installed.
 starquew depends on libccfits-dev; however:
  Package libccfits-dev is not installed.
 starquew depends on redis-server; however:
  Package redis-server is not installed.

dpkg: error processing package starquew (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 starquew

It seems a dependence problems. I intend to run indi (or indigo) server with a Rpi like (NanoPIM4) with an AllSky camera, an run the application on a linux server (larger storage and processing). A I don't know yet if "continuos shooting" will be a solution, and would need auto-gain/auto-exposure for daylight hours. Don't mind to help in your project. Good Luck

**Comment by GuLinux** [comment]
Hi,
well, that's a weird one!
In theory, running `apt install ./file.deb` instead of `dpkg` should also pull dependencies in, but that doesn't seem to be the case.
Have you tried `sudo apt -f install` after the failure?

Also, build 209 is quite old now, there are quite a lot of improvements and bugfixes in newer versions (we're at build 378 now), and plate solving is going to be merged in a few days :)

At the moment there are no autogain/autoexposure, and there's no continuous shooting as well. Still, for the latter it's an easy fix I guess, auto gain and exposure might be a lot more tricky, but depending on your camera threre might be already a setting for it (ASI cameras do have both).

If you want to start contributing the project, I'd be happy for it, and to provide the necessary help. A starter task could be picking up the continuous exposure feature

**Comment by GuLinux** [comment]
Also, try to run an `apt update` before installing StarQuew. The `python3-venv` mentioned in your error log is definitely there, so there might just be something wrong with your indexes.

**Comment by agnunez** [comment]
Thanks. Of course I tried "apt -f install" after "apt install" failure, but it doesnt solve dependencies:

$ sudo apt install ./StarQuew-0.1.1-b209-Linux.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'starquew' instead of './StarQuew-0.1.1-b209-Linux.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 starquew : Depends: python3-venv but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
$ sudo apt -f install
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

for me is suspicious this stament in 1st try:   Note, selecting 'starquew' instead of './StarQuew-0.1.1-b209-Linux.deb'

I tried cmake with your git clone but there are many missing parts (as you said). I will try binaries of 378 but tried to avoid unstable versions (as 1st step)..

I am using several ASI models (071, 294,..) so all of them support auto gain.  As soon as I get succesful installation, I will try further to compile the git clone (any help on missing modules is welcome) and I will have a look to continous exposure. BTW, I use now indigo frameworkd instead of indi, as is better suited with json instead of xml. 
Thanks

**Comment by GuLinux** [comment]
I just had a go on a new ubuntu-18.04 docker container (simulating a freshly installed system basically) and using the same version as yours (StarQuew-0.1.1-b209-Linux.deb). It installed correctly, so I'm afraid it's something on your system.
It seems to be unable to find the `python3-venv` dependency, what happens if you try to install that manually?

As for version stability, I'd say current master is not so unstable, as I tend to work on new features on branches before merging them, so the latest nightly build is pretty stable. I'd go as far to say it's currently much more stable than the current release, the only thing holding me from making a new one is that I'd like to finish at least plate solving before that.

I should have a look at indigo, it might be indeed a much better choice. How do you think it is in term of maintenance and drivers support? I guess the main advantage of indi should be that it currently is "the standard" in linux, and therefore it's more likely to receive bugfixes and new drivers support.

**Comment by agnunez** [comment]
Thanks Marco, I will try to install last version and let you know. Support
in Indigo is fantastic. I got an issue and got several answers in single
day from developers. Indigo is fully interoperable with indi as its server
recognize an legacy indi client or indi device drivers and change
automaticaly protocol from json new indigo representation to full complient
xml indi if the client (like kstars) is still using indi. Just check
StarQuew without modification against an indigo server (syntax is even
similar: $ indigo_server -vv indigo_ccd_asi .. instead of $ indiserver -vv
indi_asi_ccd, and probably your client works smoothly. I will test StarQuew
myself as soon as I manage to install it.

**Comment by GuLinux** [comment]
Hi,
closing this as the installation process changed quite a lot recently (including App rename).
If you're still experiencing issues, please feel free to open another ticket
